baseURL = "https://examplesite.com"
disqusShortname = ""
languageCode = "en"
paginate = 10
summaryLength = "20"
theme = "hargo"
title = "HHDefenders"
[[menu.footer]]
URL = "blog"
name = "Blog"
weight = 2
[params]
author = "Themefisher"
copyright = "| Copyright &copy; 2021 [Gethugothemes](https://gethugothemes.com) All Rights Reserved |"
currencySymbol = "$"
description = "This is meta description"
email = "hhdefenders@outlook.com"
googleAnalitycsID = ""
home = "Home"
location = "Centerville, Utah, USA"
logo = "images/logo.png"
mobile = "1-385-253-9855"
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
[params.contact]
formAction = "https://docs.google.com/forms/u/0/d/e/1FAIpQLSc2yV1TKFmNImaT3Klmo8jjQ_IjnvH9EDuAdp-jZMYyzcGnLw/formResponse"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = true
preloader = ""
[params.rating]
enable = true
publicKey = "811cf0927332bf51f2e12f84608594ac"
websiteID = "444334"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-instagram"
link = "#"
[[params.social]]
icon = "ti-pinterest"
link = "#"
